name: Corona-Dashboard-Scraper

on: 
  push:
    branches:
      - feature/gh-actions

jobs:

  scrape-data:

    name: Scrape, commit and push

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          sudo gem install bundler
          sudo gem update bundler
          sudo bundle install

      - name: Run Scraper
        shell: bash
        run: |
          make all
