name: Corona-Dashboard-Scraper

on: 
  push:
    branches:
      - feature/gh-actions

jobs:

  scrape-data:

    name: Scrape, commit and push

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          sudo gem install bundler
          sudo gem update bundler
          bundle install

      - name: Run Scraper
        shell: bash
        run: |
          make data

      - name: Commit and push if it changed
        shell: bash
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          timestamp=$(date "+%Y-%m-%d")
          git diff --quiet || make README.md && git add -A && git commit -m "add ${timestamp}"
          git push
